name: ctu
channels:
  - conda-forge
  - defaults

dependencies:
  # Core
  - python=3.11
  - pip
  - numpy
  - pandas
  - tqdm

  # NLP / Embeddings
  - spacy                     # core NLP
  - sentence-transformers
  - faiss-cpu=1.7.4           # arm64 build exists for py311
  - pytorch=2.1.*             # CPU build; works with py311

  # Dev / lint / tests
  - black
  - isort
  - flake8
  - pre-commit
  - pytest

  # Jupyter
  - ipykernel
  - jupyterlab

  # Optional
  - graphviz

  # Anything not on conda → pip
  - pip:
      - fasttext-wheel        # arm64 wheels via PyPI
      - spacy-langdetect
